name: docs

on:
  push:
    branches:
      - main
    paths: 
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - '**.in'
      - 'docs/doxyfile.in'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'true'

      - name: Dependencies
        shell: bash 
        run: |
          sudo apt install git
          
      - name: Configure
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake ..  -D CMAKE_BUILD_TYPE=Debug

      - name: Doxygen
        shell: bash
        run: |
          make docs

      - name: Publish
        env: 
          CI_COMMIT_MESSAGE: Auto commit
          CI_COMMIT_AUTHOR: github-actions[bot]
          CI_COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com
        shell: bash
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git fetch
          git checkout gh-pages
          git add docs/html/*
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
          
        #uses: langroodi/doxygenize@v1.6.3
        #with: 
        #  doxygenconf:   './docs/doxyfile.conf' # default is ./Doxyfile
        #  htmloutput:    './docs/html/'         # default is ./docs/
        #  ghpagesbranch: 'gh-pages'             # default is gh-pages
        #  ghpagesdir:    './docs/html/'         # default is ./ 
