name: 'docs'

on:
  push:
    branches:
      - main
    paths: 
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - 'docs/doxyfile.conf'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with: 
            submodules: "true"
          
      # Install dependencies
      - name:  Dependencies
        shell: bash
        run:   sudo apt install -y doxygen graphviz plantuml
      
      # Configure doxygen file
      - name: Configure
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake .. 
      
      # Run Doxygen
      - name: Generate Doxygen Documentation
        shell: bash
        run: doxygen ./docs/doxyfile.in
        
      # Publish doc
      - name: Push Documentation
        shell: bash
        run: ls -r ./docs && git status && git checkout gh-pages && git status
