name: docs

on:
  push:
    branches:
      - main
    paths: 
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - 'docs/doxyfile.conf'
  workflow_dispatch:

inputs:
    doxygenconf:
        description: "Location of the doxygen configuration file"
        required: true
        default:  "./docs/doxyconfig.in"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with: 
            submodules: "true"
          
      # Install dependencies
      - name:  Dependencies
        shell: bash
        run:   sudo apt install -y doxygen
      
      # Configure doxygen file
      - name: Configure
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake .. 
      
      # Run Doxygen
      - name: Generate Doxygen Documentation
        shell: bash
        run: doxygen ${{ inputs.doxygenconf }}
        
      
        
      #- name: Doxygenize
      #  uses: langroodi/doxygenize@v1.6.3
      #  with: 
      #    doxygenconf:   './docs/doxyfile.in' # default is ./Doxyfile
      #    htmloutput:    './docs/html/'       # default is ./docs/
      #    ghpagesbranch: 'gh-pages'           # default is gh-pages
      #    ghpagesdir:    './docs/html/'       # default is ./ 
