name: 'docs'

on:
  push:
    branches:
      - main
    paths: 
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - 'docs/doxyfile.conf'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository main branch
        uses: actions/checkout@v2
        with: 
            submodules: "true"
          
      # Install dependencies
      - name:  Dependencies
        shell: bash
        run:   sudo apt install -y doxygen graphviz plantuml
      
      # Configure doxygen file
      - name: Configure
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake .. 
      
      # Run Doxygen
      - name: Generate Doxygen Documentation
        shell: bash
        run: doxygen ./docs/doxyfile.in
        
       # Publish doc          
      - name: GitHub Push Documentation
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
          #repository: # optional, default is 
          # Destination branch to push changes
          branch: gh-pages # optional, default is master
          # Determines if force push is used
          #force: # optional
          # Determines if --tags is used
          #tags: # optional
          # Directory to change to before pushing.
          #directory: # optional, default is .
