name: perf

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
            submodules: 'true'

      # Install dependencies
      - name: Dependencies
        shell: bash 
        run: |
          sudo apt-get install -y python3-matplotlib

      # Configure cmake
      - name: Configure
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake .. -D CMAKE_BUILD_TYPE=Release
          make

      # Build 
      - name: Build 
        shell: bash
        run: |
          cd build
          make
      
      - name: PerfT
        shell: bash
        run: |
          cd build
          python3 perf/perf_linalg_lib.py
      
      - name: check
        shell: bash
        run: |
          ls -R docs/
