name: perf

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
            submodules: 'true'

      # Install dependencies
      - name: Dependencies
        shell: bash 
        run: |
          sudo apt-get install -y python3-matplotlib

      # Configure cmake
      - name: Configure
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake .. -D CMAKE_BUILD_TYPE=Release

      # Build 
      - name: Build 
        shell: bash
        run: |
          cd build
          make
      
      # Run performance tests
      - name: PerfT
        shell: bash
        run: |
          cd build
          python3 perf/perf_linalg_lib.py
      
      # Push results
      - name: Publish
        env: 
          CI_COMMIT_MESSAGE: Auto commit
          CI_COMMIT_AUTHOR: github-actions[bot]
        shell: bash
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git status
          git add *
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git status